language: node_js
node_js:
  - 10.14.0
script:
  - npm run build
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  keep_history: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
